const baseConfig = require("./app.json").expo;

const VARIANTS = {
  snake: {
    name: "Snake Classic",
    slug: "snake-classic",
    bundleId: "com.rngames.snake",
    androidPackage: "com.rngames.snake",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "circle-shrink": {
    name: "Circle Shrink",
    slug: "circle-shrink",
    bundleId: "com.rngames.circleshrink",
    androidPackage: "com.rngames.circleshrink",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "laser-dodge": {
    name: "Laser Dodge",
    slug: "laser-dodge",
    bundleId: "com.rngames.laserdodge",
    androidPackage: "com.rngames.laserdodge",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "pulse-lanes": {
    name: "Pulse Lanes",
    slug: "pulse-lanes",
    bundleId: "com.rngames.pulselanes",
    androidPackage: "com.rngames.pulselanes",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "math-rush": {
    name: "Math Rush",
    slug: "math-rush",
    bundleId: "com.rngames.mathrush",
    androidPackage: "com.rngames.mathrush",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "gravity-flip": {
    name: "Gravity Flip",
    slug: "gravity-flip",
    bundleId: "com.rngames.gravityflip",
    androidPackage: "com.rngames.gravityflip",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "color-clash": {
    name: "Color Clash",
    slug: "color-clash",
    bundleId: "com.rngames.colorclash",
    androidPackage: "com.rngames.colorclash",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "stack-blocks": {
    name: "Stack Blocks",
    slug: "stack-blocks",
    bundleId: "com.rngames.stackblocks",
    androidPackage: "com.rngames.stackblocks",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "simon-says": {
    name: "Simon Says",
    slug: "simon-says",
    bundleId: "com.rngames.simonsays",
    androidPackage: "com.rngames.simonsays",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "number-order": {
    name: "Number Order",
    slug: "number-order",
    bundleId: "com.rngames.numberorder",
    androidPackage: "com.rngames.numberorder",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "tap-rhythm": {
    name: "Tap Rhythm",
    slug: "tap-rhythm",
    bundleId: "com.rngames.taprhythm",
    androidPackage: "com.rngames.taprhythm",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "brick-breaker": {
    name: "Brick Breaker",
    slug: "brick-breaker",
    bundleId: "com.rngames.brickbreaker",
    androidPackage: "com.rngames.brickbreaker",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "slice-frenzy": {
    name: "Slice Frenzy",
    slug: "slice-frenzy",
    bundleId: "com.rngames.slicefrenzy",
    androidPackage: "com.rngames.slicefrenzy",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "tile-shift": {
    name: "Tile Shift",
    slug: "tile-shift",
    bundleId: "com.rngames.tileshift",
    androidPackage: "com.rngames.tileshift",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
  "color-flood": {
    name: "Color Flood",
    slug: "color-flood",
    bundleId: "com.rngames.colorflood",
    androidPackage: "com.rngames.colorflood",
    icon: "./assets/images/icon.png",
    splash: "./assets/images/splash-icon.png",
    adaptiveForeground: "./assets/images/android-icon-foreground.png",
  },
};

const requestedVariant =
  process.env.APP_VARIANT || process.env.EXPO_PUBLIC_APP_VARIANT;
const variant =
  requestedVariant && VARIANTS[requestedVariant]
    ? requestedVariant
    : undefined;
const selectedVariant = variant ? VARIANTS[variant] : null;
const VARIANT_EAS_PROJECT_IDS = {
  snake:
    process.env.EAS_PROJECT_ID_SNAKE ||
    "681d3af1-1308-4f47-82ee-750db188cae2",
  "circle-shrink": process.env.EAS_PROJECT_ID_CIRCLE_SHRINK,
  "laser-dodge": process.env.EAS_PROJECT_ID_LASER_DODGE,
  "pulse-lanes": process.env.EAS_PROJECT_ID_PULSE_LANES,
};
const resolvedEasProjectId =
  process.env.EAS_PROJECT_ID ||
  (variant ? VARIANT_EAS_PROJECT_IDS[variant] : undefined);
const DEFAULT_ANDROID_ADMOB_APP_ID = "ca-app-pub-3940256099942544~3347511713";
const DEFAULT_IOS_ADMOB_APP_ID = "ca-app-pub-3940256099942544~1458002511";

const plugins = Array.isArray(baseConfig.plugins)
  ? baseConfig.plugins
      .filter((plugin) =>
        Array.isArray(plugin)
          ? plugin[0] !== "react-native-google-mobile-ads"
          : plugin !== "react-native-google-mobile-ads",
      )
      .concat([
        [
          "react-native-google-mobile-ads",
          {
            androidAppId:
              process.env.ADMOB_ANDROID_APP_ID || DEFAULT_ANDROID_ADMOB_APP_ID,
            iosAppId: process.env.ADMOB_IOS_APP_ID || DEFAULT_IOS_ADMOB_APP_ID,
          },
        ],
      ])
  : [
      [
        "react-native-google-mobile-ads",
        {
          androidAppId:
            process.env.ADMOB_ANDROID_APP_ID || DEFAULT_ANDROID_ADMOB_APP_ID,
          iosAppId: process.env.ADMOB_IOS_APP_ID || DEFAULT_IOS_ADMOB_APP_ID,
        },
      ],
    ];

module.exports = {
  expo: {
    ...baseConfig,
    plugins,
    name: selectedVariant ? selectedVariant.name : baseConfig.name,
    slug: selectedVariant ? selectedVariant.slug : baseConfig.slug,
    icon: selectedVariant ? selectedVariant.icon : baseConfig.icon,
    splash: selectedVariant
      ? {
          image: selectedVariant.splash,
          imageWidth: 200,
          resizeMode: "contain",
          backgroundColor: "#ffffff",
          dark: { backgroundColor: "#000000" },
        }
      : baseConfig.splash,
    ios: {
      ...baseConfig.ios,
      bundleIdentifier: selectedVariant
        ? selectedVariant.bundleId
        : baseConfig.ios?.bundleIdentifier,
      infoPlist: {
        ...(baseConfig.ios?.infoPlist || {}),
        GADApplicationIdentifier:
          process.env.ADMOB_IOS_APP_ID || DEFAULT_IOS_ADMOB_APP_ID,
        // SKAdNetwork IDs for iOS 14+ attribution (TopOn ADX v6.4.87 + all mediation partners)
        // Required for all ad networks to report installs/conversions on iOS 14+
        SKAdNetworkItems: [
          { SKAdNetworkIdentifier: "4w7y6s5ca2.skadnetwork" },
          { SKAdNetworkIdentifier: "44jx6755aq.skadnetwork" },
          { SKAdNetworkIdentifier: "9rd848q2bz.skadnetwork" },
          { SKAdNetworkIdentifier: "tl55sbb4fm.skadnetwork" },
          { SKAdNetworkIdentifier: "9t245vhmpl.skadnetwork" },
          { SKAdNetworkIdentifier: "a8cz6cu7e5.skadnetwork" },
          { SKAdNetworkIdentifier: "424m5254lk.skadnetwork" },
          { SKAdNetworkIdentifier: "wg4vff78zm.skadnetwork" },
          { SKAdNetworkIdentifier: "n9x2a789qt.skadnetwork" },
          { SKAdNetworkIdentifier: "s39g8k73mm.skadnetwork" },
          { SKAdNetworkIdentifier: "prcb7njmu6.skadnetwork" },
          { SKAdNetworkIdentifier: "238da6jt44.skadnetwork" },
          { SKAdNetworkIdentifier: "mlmmfzh3r3.skadnetwork" },
          { SKAdNetworkIdentifier: "mj797d8u6f.skadnetwork" },
          { SKAdNetworkIdentifier: "vhf287vqwu.skadnetwork" },
          { SKAdNetworkIdentifier: "5l3tpt7t6e.skadnetwork" },
          { SKAdNetworkIdentifier: "hs6bdukanm.skadnetwork" },
          { SKAdNetworkIdentifier: "wzmmz9fp6w.skadnetwork" },
          { SKAdNetworkIdentifier: "f38h382jlk.skadnetwork" },
          { SKAdNetworkIdentifier: "glqzh8vgby.skadnetwork" },
          { SKAdNetworkIdentifier: "5a6flpkh64.skadnetwork" },
          { SKAdNetworkIdentifier: "294l99pt4k.skadnetwork" },
          { SKAdNetworkIdentifier: "c6k4g5qg8m.skadnetwork" },
          { SKAdNetworkIdentifier: "4fzdc2evr5.skadnetwork" },
          { SKAdNetworkIdentifier: "x44k69ngh6.skadnetwork" },
          { SKAdNetworkIdentifier: "p78axxw29g.skadnetwork" },
          { SKAdNetworkIdentifier: "k6y4y55b64.skadnetwork" },
          { SKAdNetworkIdentifier: "5f5u5tfb26.skadnetwork" },
          { SKAdNetworkIdentifier: "7ug5zh24hu.skadnetwork" },
          { SKAdNetworkIdentifier: "f7s53z58qe.skadnetwork" },
          { SKAdNetworkIdentifier: "488r3q3dtq.skadnetwork" },
          { SKAdNetworkIdentifier: "t38b2kh725.skadnetwork" },
          { SKAdNetworkIdentifier: "e5fvkxwrpn.skadnetwork" },
          { SKAdNetworkIdentifier: "3qy4746246.skadnetwork" },
          { SKAdNetworkIdentifier: "32z4fx6l9h.skadnetwork" },
          { SKAdNetworkIdentifier: "9nlqeag3gk.skadnetwork" },
          { SKAdNetworkIdentifier: "m8dbw4sv7c.skadnetwork" },
          { SKAdNetworkIdentifier: "97r2b46745.skadnetwork" },
          { SKAdNetworkIdentifier: "4pfyvq9l8r.skadnetwork" },
          { SKAdNetworkIdentifier: "w9q455wk68.skadnetwork" },
          { SKAdNetworkIdentifier: "yclnxrl5pm.skadnetwork" },
          { SKAdNetworkIdentifier: "zmvfpc5aq8.skadnetwork" },
          { SKAdNetworkIdentifier: "xga6mpmplv.skadnetwork" },
          { SKAdNetworkIdentifier: "5tjdwbrq8w.skadnetwork" },
          { SKAdNetworkIdentifier: "cstr6suwn9.skadnetwork" },
          { SKAdNetworkIdentifier: "5lm9lj6jb7.skadnetwork" },
          { SKAdNetworkIdentifier: "22mmun2rn5.skadnetwork" },
          { SKAdNetworkIdentifier: "ppxm28t8ap.skadnetwork" },
          { SKAdNetworkIdentifier: "f73kdq92p3.skadnetwork" },
          { SKAdNetworkIdentifier: "v9wttpbfk9.skadnetwork" },
          { SKAdNetworkIdentifier: "3sh42y64q3.skadnetwork" },
          { SKAdNetworkIdentifier: "v79kvwwj4g.skadnetwork" },
          { SKAdNetworkIdentifier: "ydx93a7ass.skadnetwork" },
          { SKAdNetworkIdentifier: "k674qkevps.skadnetwork" },
          { SKAdNetworkIdentifier: "av6w8kgt66.skadnetwork" },
          { SKAdNetworkIdentifier: "578prtvx9j.skadnetwork" },
          { SKAdNetworkIdentifier: "uw77j35x4d.skadnetwork" },
          { SKAdNetworkIdentifier: "8s468mfl3y.skadnetwork" },
          { SKAdNetworkIdentifier: "pwa73g5rt2.skadnetwork" },
          { SKAdNetworkIdentifier: "3rd42ekr43.skadnetwork" },
          { SKAdNetworkIdentifier: "4dzt52r2t5.skadnetwork" },
          { SKAdNetworkIdentifier: "feyaarzu9v.skadnetwork" },
          { SKAdNetworkIdentifier: "g6gcrrvk4p.skadnetwork" },
          { SKAdNetworkIdentifier: "lr83yxwka7.skadnetwork" },
          { SKAdNetworkIdentifier: "2u9pt9hc89.skadnetwork" },
          { SKAdNetworkIdentifier: "v72qych5uu.skadnetwork" },
          { SKAdNetworkIdentifier: "mqn7fxpca7.skadnetwork" },
          { SKAdNetworkIdentifier: "kbd757ywx3.skadnetwork" },
          { SKAdNetworkIdentifier: "2fnua5tdw4.skadnetwork" },
          { SKAdNetworkIdentifier: "6yxyv74ff7.skadnetwork" },
          { SKAdNetworkIdentifier: "klf5c3l5u5.skadnetwork" },
          { SKAdNetworkIdentifier: "mp6xlyr22a.skadnetwork" },
          { SKAdNetworkIdentifier: "4468km3ulz.skadnetwork" },
          { SKAdNetworkIdentifier: "a2p9lx4jpn.skadnetwork" },
          { SKAdNetworkIdentifier: "zq492l623r.skadnetwork" },
          { SKAdNetworkIdentifier: "mls7yz5dvl.skadnetwork" },
          { SKAdNetworkIdentifier: "cg4yq2srnc.skadnetwork" },
          { SKAdNetworkIdentifier: "737z793b9f.skadnetwork" },
          { SKAdNetworkIdentifier: "6xzpu9s2p8.skadnetwork" },
          { SKAdNetworkIdentifier: "ludvb6z3bs.skadnetwork" },
          { SKAdNetworkIdentifier: "523jb4fst2.skadnetwork" },
          { SKAdNetworkIdentifier: "ggvn48r87g.skadnetwork" },
          { SKAdNetworkIdentifier: "24t9a8vw3c.skadnetwork" },
          { SKAdNetworkIdentifier: "cj5566h2ga.skadnetwork" },
          { SKAdNetworkIdentifier: "7rz58n8ntl.skadnetwork" },
          { SKAdNetworkIdentifier: "ejvt5qm6ak.skadnetwork" },
          { SKAdNetworkIdentifier: "dzg6xy7pwj.skadnetwork" },
          { SKAdNetworkIdentifier: "y45688jllp.skadnetwork" },
          { SKAdNetworkIdentifier: "hdw39hrw9y.skadnetwork" },
          { SKAdNetworkIdentifier: "mtkv5xtk9e.skadnetwork" },
          { SKAdNetworkIdentifier: "gta9lk7p23.skadnetwork" },
          { SKAdNetworkIdentifier: "g28c52eehv.skadnetwork" },
          { SKAdNetworkIdentifier: "su67r6k2v3.skadnetwork" },
          { SKAdNetworkIdentifier: "rx5hdcabgc.skadnetwork" },
          { SKAdNetworkIdentifier: "xy9t38ct57.skadnetwork" },
          { SKAdNetworkIdentifier: "54nzkqm89y.skadnetwork" },
          { SKAdNetworkIdentifier: "9b89h5y424.skadnetwork" },
          { SKAdNetworkIdentifier: "79pbpufp6p.skadnetwork" },
          { SKAdNetworkIdentifier: "kbmxgpxpgc.skadnetwork" },
          { SKAdNetworkIdentifier: "275upjj5gd.skadnetwork" },
          { SKAdNetworkIdentifier: "rvh3l7un93.skadnetwork" },
          { SKAdNetworkIdentifier: "qqp299437r.skadnetwork" },
          { SKAdNetworkIdentifier: "74b6s63p6l.skadnetwork" },
          { SKAdNetworkIdentifier: "44n7hlldy6.skadnetwork" },
          { SKAdNetworkIdentifier: "6p4ks3rnbw.skadnetwork" },
          { SKAdNetworkIdentifier: "3qcr597p9d.skadnetwork" },
          { SKAdNetworkIdentifier: "n6fk4nfna4.skadnetwork" },
          { SKAdNetworkIdentifier: "b9bk5wbcq9.skadnetwork" },
          { SKAdNetworkIdentifier: "84993kbrcf.skadnetwork" },
          { SKAdNetworkIdentifier: "24zw6aqk47.skadnetwork" },
          { SKAdNetworkIdentifier: "pwdxu55a5a.skadnetwork" },
          { SKAdNetworkIdentifier: "cs644xg564.skadnetwork" },
          { SKAdNetworkIdentifier: "6964rsfnh4.skadnetwork" },
          { SKAdNetworkIdentifier: "9vvzujtq5s.skadnetwork" },
          { SKAdNetworkIdentifier: "a7xqa6mtl2.skadnetwork" },
          { SKAdNetworkIdentifier: "r45fhb6rf7.skadnetwork" },
          { SKAdNetworkIdentifier: "c3frkrj4fj.skadnetwork" },
          { SKAdNetworkIdentifier: "6g9af3uyq4.skadnetwork" },
          { SKAdNetworkIdentifier: "u679fj5vs4.skadnetwork" },
          { SKAdNetworkIdentifier: "g2y4y55b64.skadnetwork" },
          { SKAdNetworkIdentifier: "dbu4b84rxf.skadnetwork" },
          { SKAdNetworkIdentifier: "ns5j362hk7.skadnetwork" },
          { SKAdNetworkIdentifier: "252b5q8x7y.skadnetwork" },
          { SKAdNetworkIdentifier: "7fmhfwg9en.skadnetwork" },
          { SKAdNetworkIdentifier: "cwn433xbcr.skadnetwork" },
          { SKAdNetworkIdentifier: "7953jerfzd.skadnetwork" },
          { SKAdNetworkIdentifier: "qu637u8glc.skadnetwork" },
          { SKAdNetworkIdentifier: "9yg77x724h.skadnetwork" },
          { SKAdNetworkIdentifier: "n66cz3y3bx.skadnetwork" },
          { SKAdNetworkIdentifier: "z959bm4gru.skadnetwork" },
          { SKAdNetworkIdentifier: "s69wq72ugq.skadnetwork" },
          { SKAdNetworkIdentifier: "x8uqf25wch.skadnetwork" },
          { SKAdNetworkIdentifier: "bxvub5ada5.skadnetwork" },
          { SKAdNetworkIdentifier: "krvm3zuq6h.skadnetwork" },
          { SKAdNetworkIdentifier: "8r8llnkz5a.skadnetwork" },
          { SKAdNetworkIdentifier: "47vhws6wlr.skadnetwork" },
          { SKAdNetworkIdentifier: "8c4e2ghe7u.skadnetwork" },
          { SKAdNetworkIdentifier: "cp8zw746q7.skadnetwork" },
          { SKAdNetworkIdentifier: "ecpz2srf59.skadnetwork" },
          { SKAdNetworkIdentifier: "eh6m2bh4zr.skadnetwork" },
          { SKAdNetworkIdentifier: "n38lu8286q.skadnetwork" },
          { SKAdNetworkIdentifier: "v4nxqhlyqp.skadnetwork" },
          { SKAdNetworkIdentifier: "vutu7akeur.skadnetwork" },
          { SKAdNetworkIdentifier: "y5ghdn5j9k.skadnetwork" },
          { SKAdNetworkIdentifier: "3l6bd9hu43.skadnetwork" },
          { SKAdNetworkIdentifier: "52fl2v3hgk.skadnetwork" },
          { SKAdNetworkIdentifier: "6v7lgmsu45.skadnetwork" },
          { SKAdNetworkIdentifier: "89z7zv988g.skadnetwork" },
          { SKAdNetworkIdentifier: "8m87ys6875.skadnetwork" },
          { SKAdNetworkIdentifier: "bvpn9ufa9b.skadnetwork" },
          { SKAdNetworkIdentifier: "gvmwg8q7h5.skadnetwork" },
          { SKAdNetworkIdentifier: "hb56zgv37p.skadnetwork" },
          { SKAdNetworkIdentifier: "hjevpa356n.skadnetwork" },
          { SKAdNetworkIdentifier: "m297p6643m.skadnetwork" },
          { SKAdNetworkIdentifier: "m5mvw97r93.skadnetwork" },
          { SKAdNetworkIdentifier: "nzq8sh4pbs.skadnetwork" },
          { SKAdNetworkIdentifier: "pu4na253f3.skadnetwork" },
          { SKAdNetworkIdentifier: "vcra2ehyfk.skadnetwork" },
          { SKAdNetworkIdentifier: "yrqqpx2mcb.skadnetwork" },
          { SKAdNetworkIdentifier: "z4gj7hsk7h.skadnetwork" },
          { SKAdNetworkIdentifier: "4mn522wn87.skadnetwork" },
          { SKAdNetworkIdentifier: "dkc879ngq3.skadnetwork" },
          { SKAdNetworkIdentifier: "gta8lk7p23.skadnetwork" },
          { SKAdNetworkIdentifier: "x5l83yy675.skadnetwork" },
          { SKAdNetworkIdentifier: "x8jxxk4ff5.skadnetwork" },
          { SKAdNetworkIdentifier: "z24wtl6j62.skadnetwork" },
          { SKAdNetworkIdentifier: "9g2aggbj52.skadnetwork" },
          { SKAdNetworkIdentifier: "h65wbv5k3f.skadnetwork" },
          { SKAdNetworkIdentifier: "t6d3zquu66.skadnetwork" },
          { SKAdNetworkIdentifier: "tvvz7th9br.skadnetwork" },
          { SKAdNetworkIdentifier: "nu4557a4je.skadnetwork" },
          { SKAdNetworkIdentifier: "55644vm79v.skadnetwork" },
          { SKAdNetworkIdentifier: "w7jznl3r6g.skadnetwork" },
          { SKAdNetworkIdentifier: "577p5t736z.skadnetwork" },
          { SKAdNetworkIdentifier: "6rd35atwn8.skadnetwork" },
          { SKAdNetworkIdentifier: "7bxrt786m8.skadnetwork" },
          { SKAdNetworkIdentifier: "7fbxrn65az.skadnetwork" },
          { SKAdNetworkIdentifier: "ce8ybjwass.skadnetwork" },
          { SKAdNetworkIdentifier: "dt3cjx1a9i.skadnetwork" },
          { SKAdNetworkIdentifier: "fz2k2k5tej.skadnetwork" },
          { SKAdNetworkIdentifier: "jk2fsx2rgz.skadnetwork" },
          { SKAdNetworkIdentifier: "ln5gz23vtd.skadnetwork" },
          { SKAdNetworkIdentifier: "r8lj5b58b5.skadnetwork" },
          { SKAdNetworkIdentifier: "tmhh9296z4.skadnetwork" },
          { SKAdNetworkIdentifier: "qwpu75vrh2.skadnetwork" },
          { SKAdNetworkIdentifier: "55y65gfgn7.skadnetwork" },
          { SKAdNetworkIdentifier: "fq6vru337s.skadnetwork" },
          { SKAdNetworkIdentifier: "87u5trcl3r.skadnetwork" },
          { SKAdNetworkIdentifier: "bd757ywx3.skadnetwork" },
          { SKAdNetworkIdentifier: "33r6p7g8nc.skadnetwork" },
          { SKAdNetworkIdentifier: "g69uk9uh2b.skadnetwork" },
          { SKAdNetworkIdentifier: "633vhxswh4.skadnetwork" },
          { SKAdNetworkIdentifier: "zh3b7bxvad.skadnetwork" },
          { SKAdNetworkIdentifier: "xmn954pzmp.skadnetwork" },
          { SKAdNetworkIdentifier: "79w64w269u.skadnetwork" },
          { SKAdNetworkIdentifier: "d7g9azk84q.skadnetwork" },
          { SKAdNetworkIdentifier: "866k9ut3g3.skadnetwork" },
          { SKAdNetworkIdentifier: "2q884k2j68.skadnetwork" },
          { SKAdNetworkIdentifier: "gfat3222tu.skadnetwork" },
          { SKAdNetworkIdentifier: "pd25vrrwzn.skadnetwork" },
          { SKAdNetworkIdentifier: "y755zyxw56.skadnetwork" },
          { SKAdNetworkIdentifier: "qlbq5gtkt8.skadnetwork" },
          { SKAdNetworkIdentifier: "67369282zy.skadnetwork" },
          { SKAdNetworkIdentifier: "899vrgt9g8.skadnetwork" },
          { SKAdNetworkIdentifier: "88k8774x49.skadnetwork" },
          { SKAdNetworkIdentifier: "t3b3f7n3x8.skadnetwork" },
          { SKAdNetworkIdentifier: "c7g47wypnu.skadnetwork" },
          { SKAdNetworkIdentifier: "z5b3gh5ugf.skadnetwork" },
          { SKAdNetworkIdentifier: "dd3a75yxkv.skadnetwork" },
          { SKAdNetworkIdentifier: "h5jmj969g5.skadnetwork" },
          { SKAdNetworkIdentifier: "dr774724x4.skadnetwork" },
          { SKAdNetworkIdentifier: "t7ky8fmwkd.skadnetwork" },
          { SKAdNetworkIdentifier: "w28pnjg2k4.skadnetwork" },
          { SKAdNetworkIdentifier: "2rq3zucswp.skadnetwork" },
          { SKAdNetworkIdentifier: "vc83br9sjg.skadnetwork" },
          { SKAdNetworkIdentifier: "eqhxz8m8av.skadnetwork" },
          { SKAdNetworkIdentifier: "7k3cvf297u.skadnetwork" },
          { SKAdNetworkIdentifier: "7tnzynbdc7.skadnetwork" },
          { SKAdNetworkIdentifier: "l6nv3x923s.skadnetwork" },
          { SKAdNetworkIdentifier: "h8vml93bkz.skadnetwork" },
          { SKAdNetworkIdentifier: "uzqba5354d.skadnetwork" },
          { SKAdNetworkIdentifier: "8qiegk9qfv.skadnetwork" },
          { SKAdNetworkIdentifier: "xx9sdjej2w.skadnetwork" },
          { SKAdNetworkIdentifier: "au67k4efj4.skadnetwork" },
          { SKAdNetworkIdentifier: "dmv22haz9p.skadnetwork" },
          { SKAdNetworkIdentifier: "b55w3d8y8z.skadnetwork" },
          { SKAdNetworkIdentifier: "v7896pgt74.skadnetwork" },
          { SKAdNetworkIdentifier: "5ghnmfs3dh.skadnetwork" },
          { SKAdNetworkIdentifier: "627r9wr2y5.skadnetwork" },
          { SKAdNetworkIdentifier: "sczv5946wb.skadnetwork" },
          { SKAdNetworkIdentifier: "8w3np9l82g.skadnetwork" },
          { SKAdNetworkIdentifier: "nrt9jy4kw9.skadnetwork" },
          { SKAdNetworkIdentifier: "dn942472g5.skadnetwork" },
          { SKAdNetworkIdentifier: "cad8qz2s3j.skadnetwork" },
          { SKAdNetworkIdentifier: "r26jy69rpl.skadnetwork" },
          { SKAdNetworkIdentifier: "jb7bn6koa5.skadnetwork" },
          { SKAdNetworkIdentifier: "fkak3gfpt6.skadnetwork" },
          { SKAdNetworkIdentifier: "2tdux39lx8.skadnetwork" },
          { SKAdNetworkIdentifier: "3cgn6rq224.skadnetwork" },
          { SKAdNetworkIdentifier: "nfqy3847ph.skadnetwork" },
          { SKAdNetworkIdentifier: "dticjx1a9i.skadnetwork" },
          { SKAdNetworkIdentifier: "9wsyqb3ku7.skadnetwork" },
          { SKAdNetworkIdentifier: "x5854y7y24.skadnetwork" },
          { SKAdNetworkIdentifier: "6qx585k4p6.skadnetwork" },
          { SKAdNetworkIdentifier: "l93v5h6a4m.skadnetwork" },
          { SKAdNetworkIdentifier: "axh5283zss.skadnetwork" },
          { SKAdNetworkIdentifier: "5mv394q32t.skadnetwork" },
          { SKAdNetworkIdentifier: "x2jnk7ly8j.skadnetwork" },
        ],
      },
    },
    android: {
      ...baseConfig.android,
      package: selectedVariant
        ? selectedVariant.androidPackage
        : baseConfig.android?.package,
      adaptiveIcon: {
        ...baseConfig.android?.adaptiveIcon,
        foregroundImage: selectedVariant
          ? selectedVariant.adaptiveForeground
          : baseConfig.android?.adaptiveIcon?.foregroundImage,
      },
    },
    extra: {
      ...(baseConfig.extra || {}),
      eas: {
        ...(baseConfig.extra?.eas || {}),
        ...(resolvedEasProjectId ? { projectId: resolvedEasProjectId } : {}),
      },
      ...(variant ? { appVariant: variant } : {}),
    },
  },
};
